--- #YAML:1.0
name:               Cicada
version:            0.01
abstract:           Web Crawler creating toolkit 
author:
    - Makio Tsukamoto <tsukamoto@gmail.com>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Carp:        1.1
    File::Path:  2.07
    Test::More:  0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.50
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
